# deduced with the aid of chatGPT
CITIES_REGIONS_MAP = {
    "100 mile house": "Interior",
    "108 mile ranch": "Interior",
    "150 mile house": "Interior",
    "abbotsford": "Coast Fraser",
    "agassiz": "Coast Fraser",
    "ahousat": "Vancouver Island",
    "aldergrove": "Coast Fraser",
    "alert bay": "Vancouver Island",
    "alkali lake": "Interior",
    "anmore": "Coast Fraser",
    "armstrong": "Interior",
    "ashcroft": "Interior",
    "atlin": "Interior",
    "balfour": "Interior",
    "bamfield": "Vancouver Island",
    "barriere": "Interior",
    "bella bella": "Coast Fraser",
    "bella coola": "Coast Fraser",
    "black creek": "Vancouver Island",
    "blind bay": "Interior",
    "bowen island": "Coast Fraser",
    "brackendale": "Coast Fraser",
    "brentwood bay": "Vancouver Island",
    "burnaby": "Coast Fraser",
    "burns lake": "Interior",
    "cache creek": "Interior",
    "campbell river": "Vancouver Island",
    "canal flats": "Interior",
    "canim lake": "Interior",
    "canoe creek": "Interior",
    "castlegar": "Interior",
    "cawston": "Interior",
    "celista": "Interior",
    "charlie lake": "North",
    "chase": "Interior",
    "chemainus": "Vancouver Island",
    "cherryville": "Interior",
    "chetwynd": "North",
    "chilliwack": "Coast Fraser",
    "christina lake": "Interior",
    "clearwater": "Interior",
    "coal harbour": "Vancouver Island",
    "cobble hill": "Vancouver Island",
    "coldstream": "Interior",
    "colwood": "Vancouver Island",
    "comox": "Vancouver Island",
    "coombs": "Vancouver Island",
    "coquitlam": "Coast Fraser",
    "courtenay": "Vancouver Island",
    "cowichan bay": "Vancouver Island",
    "cranbrook": "Interior",
    "crescent valley": "Interior",
    "creston": "Interior",
    "crofton": "Vancouver Island",
    "cultus lake": "Coast Fraser",
    "cumberland": "Vancouver Island",
    "d'arcy": "Coast Fraser",
    "darcy": "Coast Fraser",
    "dawson creek": "North",
    "delta": "Coast Fraser",
    "denman island": "Vancouver Island",
    "duncan": "Vancouver Island",
    "edgewater": "Interior",
    "elkford": "Interior",
    "enderby": "Interior",
    "errington": "Vancouver Island",
    "esquimalt": "Vancouver Island",
    "falkland": "Interior",
    "fanny bay": "Vancouver Island",
    "fernie": "Interior",
    "fort langley": "Coast Fraser",
    "fort nelson": "North",
    "fort st john": "North",
    "fort st. james": "North",
    "fraser lake": "North",
    "fruitvale": "Interior",
    "gabriola": "Vancouver Island",
    "galiano island": "Vancouver Island",
    "garibaldi highlands": "Coast Fraser",
    "gibsons": "Coast Fraser",
    "gold river": "Vancouver Island",
    "golden": "Interior",
    "grand forks": "Interior",
    "hagensborg": "Coast Fraser",
    "halfmoon bay": "Coast Fraser",
    "harrison hot springs": "Coast Fraser",
    "hazelton": "Coast Fraser",
    "hedley": "Interior",
    "hope": "Coast Fraser",
    "houston": "North",
    "hudson's hope": "North",
    "invermere": "Interior",
    "kaleden": "Interior",
    "kamloops": "Interior",
    "kaslo": "Interior",
    "kelowna": "Interior",
    "keremeos": "Interior",
    "kimberley": "Interior",
    "kispiox": "Coast Fraser",
    "kitimat": "Coast Fraser",
    "kitwanga": "Coast Fraser",
    "ladysmith": "Vancouver Island",
    "lake country": "Interior",
    "lake cowichan": "Vancouver Island",
    "langely": "Coast Fraser",
    "langford": "Vancouver Island",
    "lantzville": "Vancouver Island",
    "lazo": "Vancouver Island",
    "lillooet": "Interior",
    "lions bay": "Coast Fraser",
    "logan lake": "Interior",
    "lumby": "Interior",
    "lund": "Vancouver Island",
    "mackenzie": "North",
    "madeira park": "Coast Fraser",
    "malakwa": "Interior",
    "mansons landing": "Coast Fraser",
    "maple ridge": "Coast Fraser",
    "mayne island": "Vancouver Island",
    "mcbride": "North",
    "merritt": "Interior",
    "merville": "Vancouver Island",
    "mill bay": "Vancouver Island",
    "mission": "Coast Fraser",
    "moberly lake": "North",
    "montrose": "Interior",
    "nakusp": "Interior",
    "nanaimo": "Vancouver Island",
    "nanoose bay": "Vancouver Island",
    "naramata": "Interior",
    "nelson": "Interior",
    "new denver": "Interior",
    "new westminster": "Coast Fraser",
    "north saanich": "Vancouver Island",
    "north vancouver": "Coast Fraser",
    "okanagan falls": "Interior",
    "oliver": "Interior",
    "osoyoos": "Interior",
    "oyama": "Interior",
    "parksville": "Vancouver Island",
    "peachland": "Interior",
    "pemberton": "Coast Fraser",
    "pender island": "Vancouver Island",
    "penticton": "Interior",
    "pitt meadows": "Coast Fraser",
    "port alberni": "Vancouver Island",
    "port coquitlam": "Coast Fraser",
    "port hardy": "Vancouver Island",
    "port mcneill": "Vancouver Island",
    "port moody": "Coast Fraser",
    "powell river": "Coast Fraser",
    "prince george": "North",
    "prince rupert": "North",
    "princeton": "Interior",
    "qualicum beach": "Vancouver Island",
    "queen charlotte": "Coast Fraser",
    "quesnel": "Interior",
    "radium hot springs": "Interior",
    "revelstoke": "Interior",
    "richmond": "Coast Fraser",
    "roberts creek": "Coast Fraser",
    "robson": "Interior",
    "rosedale": "Interior",
    "rossland": "Interior",
    "royston": "Vancouver Island",
    "saanich": "Vancouver Island",
    "saanichton": "Vancouver Island",
    "salmon arm": "Interior",
    "salt spring island": "Vancouver Island",
    "savona": "Interior",
    "sayward": "Vancouver Island",
    "sechelt": "Coast Fraser",
    "shawnigan lake": "Vancouver Island",
    "sicamous": "Interior",
    "sidney": "Vancouver Island",
    "skidegate": "Coast Fraser",
    "smithers": "North",
    "sooke": "Vancouver Island",
    "sorrento": "Interior",
    "south slocan": "Interior",
    "sparwood": "Interior",
    "squamish": "Coast Fraser",
    "summerland": "Interior",
    "sun peaks": "Interior",
    "surrey": "Coast Fraser",
    "tappen": "Interior",
    "taylor": "North",
    "terrace": "North",
    "thornhill": "North",
    "tofino": "Vancouver Island",
    "trail": "Interior",
    "tsawwassen": "Coast Fraser",
    "tumbler ridge": "North",
    "ucluelet": "Vancouver Island",
    "union bay": "Vancouver Island",
    "vancouver": "Coast Fraser",
    "vanderhoof": "North",
    "vernon": "Interior",
    "victoria": "Vancouver Island",
    "ware": "North",
    "west creston": "Interior",
    "west kelowna": "Interior",
    "west vancouver": "Coast Fraser",
    "westbank": "Interior",
    "whistler": "Coast Fraser",
    "white rock": "Coast Fraser",
    "williams lake": "Interior",
    "windermere": "Interior",
    "winfield": "Interior",
    "winlaw": "Interior",
    "yarrow": "Coast Fraser",
    # manual additions
    "fort st. john": "North",
    "langley": "Coast Fraser",
}

DATA_SOURCES = {
    "facilities and spaces over time": "https://catalogue.data.gov.bc.ca/dataset/b67255a7-8040-43c0-935c-d74f168af215/resource/63d9b10c-ec0b-432c-9291-e7b3db8c7e96/download/ccof_facilities_and_spaces_over_time.csv",
    "child care map data": "https://catalogue.data.gov.bc.ca/dataset/4cc207cc-ff03-44f8-8c5f-415af5224646/resource/9a9f14e1-03ea-4a11-936a-6e77b15eeb39/download/childcare_locations.csv",
}

NAME_MAPPINGS = {
    'region': 'Region',
    'group_facilities': 'Group Facilities',
    'group_facilities_change': 'Group Facilities Changes',
    'total_facilities': 'Total Facilities',
    'total_spaces':'Total Spaces',
    'family_spaces': 'Family Spaces',
    'date': 'Date',
    'CITY': 'City'
}

BC_CENTRE_LAT_LON = [49.2827, -123.1207]